apiVersion: v1
kind: Pod
metadata:
  name: myenvconfig
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo HelloWorld; sleep 5 ; done"]
    env:
    - name: MYENV
      valueFrom:
        configMapKeyRef:
          name: mymap       #wherever it created obj with name mymap, there it will check for sample.conf config file
          key: sample.conf
      
